/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import javax.swing.JOptionPane;
import uam.azc.adsi.cinetubi.controller.PeliculaController;
import uam.azc.adsi.cinetubi.model.Pelicula;

/**
 *
 * @author Jony
 */
public class AgregarPeliculaVista extends javax.swing.JFrame {
    private PeliculaController peliculaController;

    /**
     * Creates new form AgregarPeliculaVista
     */
    public AgregarPeliculaVista(PeliculaController peliculaController) {
        this.peliculaController = peliculaController;
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JTextField();
        jLgenero = new javax.swing.JLabel();
        jLduracion = new javax.swing.JLabel();
        jTduracion = new javax.swing.JTextField();
        jLclasificacion = new javax.swing.JLabel();
        jLdistribuidora = new javax.swing.JLabel();
        jTdistribuidora = new javax.swing.JTextField();
        cb_genero = new javax.swing.JComboBox<>();
        cb_clasif = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAsipnosis = new javax.swing.JTextArea();
        jLsipnosis = new javax.swing.JLabel();
        jLdirector = new javax.swing.JLabel();
        jTdirector = new javax.swing.JTextField();
        jLpais = new javax.swing.JLabel();
        jTpais = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitulo.setText("Titulo");

        jTtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtituloActionPerformed(evt);
            }
        });

        jLgenero.setText("Genero");

        jLduracion.setText("Duracion");

        jTduracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTduracionActionPerformed(evt);
            }
        });

        jLclasificacion.setText("Clasificación");

        jLdistribuidora.setText("Distribuidora");

        jTdistribuidora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdistribuidoraActionPerformed(evt);
            }
        });

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Comedia", "Drama", "Terror", "Fantasia" }));
        cb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_generoActionPerformed(evt);
            }
        });

        cb_clasif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "PG", "M", "MA", "R" }));

        jTAsipnosis.setColumns(20);
        jTAsipnosis.setRows(5);
        jScrollPane1.setViewportView(jTAsipnosis);

        jLsipnosis.setText("Sipnosis");

        jLdirector.setText("Director");

        jTdirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdirectorActionPerformed(evt);
            }
        });

        jLpais.setText("País");

        jTpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpaisActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLabel7.setText("Agregar Pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLtitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTtitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLgenero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLduracion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTduracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jLclasificacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdistribuidora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTdistribuidora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(cb_genero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_clasif, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLsipnosis)
                            .addComponent(jLpais)
                            .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLdirector)
                            .addComponent(jTdirector, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBguardar)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtitulo)
                    .addComponent(jLsipnosis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLgenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLduracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLclasificacion)
                    .addComponent(jLpais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_clasif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLdistribuidora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLdirector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBVolver))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
        public String getTitulo() {
        return jTtitulo.getText();
    }

    public String getGenero() {
        return (String) cb_genero.getSelectedItem();
    }

    public String getDuracion() {
        return jTduracion.getText();
    }

    public String getClasificacion() {
        return (String) cb_clasif.getSelectedItem();
    }

    public String getDistribuidora() {
        return jTdistribuidora.getText();
    }

    public String getSinopsis() {
        return jTAsipnosis.getText();
    }

    private void jTtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtituloActionPerformed

    private void jTduracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTduracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTduracionActionPerformed

    private void jTdistribuidoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdistribuidoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdistribuidoraActionPerformed

    private void jTdirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdirectorActionPerformed

    private void jTpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpaisActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
// Recoger datos del formulario
                String titulo = jTtitulo.getText();
                String genero = (String) cb_genero.getSelectedItem();
                int duracion = Integer.parseInt(jTduracion.getText());
                String clasificacion = (String) cb_clasif.getSelectedItem();
                String distribuidora = jTdistribuidora.getText();
                String sinopsis = jTAsipnosis.getText();
                String pais = jTpais.getText();
                String director = jTdirector.getText();

                // Crear objeto Pelicula
                Pelicula nuevaPelicula = new Pelicula();
                nuevaPelicula.setTitulo(titulo);
                nuevaPelicula.setDuracion(duracion);
                nuevaPelicula.setDistribuidor(distribuidora);
                nuevaPelicula.setClasificacion(clasificacion);
                nuevaPelicula.setDescripcion(sinopsis);
                nuevaPelicula.setPais(pais);
                nuevaPelicula.setGenero(genero);
                nuevaPelicula.setDirector(director);

                // Guardar película en la base de datos
                try {
                    
                    peliculaController.agregarPelicula(nuevaPelicula);
                    JOptionPane.showMessageDialog(null, "Película guardada exitosamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al guardar la película: " + ex.getMessage());
                }
                }//GEN-LAST:event_jBguardarActionPerformed

    private void cb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_generoActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        dispose();
        MenuProgramacion menu = new MenuProgramacion();
        menu.setVisible(true);
        
        
        
    }//GEN-LAST:event_jBVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_clasif;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JButton jBVolver;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLclasificacion;
    private javax.swing.JLabel jLdirector;
    private javax.swing.JLabel jLdistribuidora;
    private javax.swing.JLabel jLduracion;
    private javax.swing.JLabel jLgenero;
    private javax.swing.JLabel jLpais;
    private javax.swing.JLabel jLsipnosis;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAsipnosis;
    private javax.swing.JTextField jTdirector;
    private javax.swing.JTextField jTdistribuidora;
    private javax.swing.JTextField jTduracion;
    private javax.swing.JTextField jTpais;
    private javax.swing.JTextField jTtitulo;
    // End of variables declaration//GEN-END:variables
}
