/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uam.azc.adsi.cinetubi.controller.PeliculaController;
import uam.azc.adsi.cinetubi.dao.FuncionDAO;
import uam.azc.adsi.cinetubi.dao.PeliculaDAO;
import uam.azc.adsi.cinetubi.model.Funcion;
import uam.azc.adsi.cinetubi.model.Pelicula;
import uam.azc.adsi.cinetubi.util.DatabaseConnection;

/**
 *
 * @author Jony
 */
public class EditarPelicula extends javax.swing.JFrame {

    /**
     * Creates new form EditarPelicula
     */
    public EditarPelicula() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarPeliculas();
    }
    
    
    
    public void cargarPeliculas(){
        
        try {
            String[] columnNames = {"id","Nombre","Duración","Distribuidor", "Clasificación", "Director", "País", "Descripción"};
            
            DefaultTableModel model = new DefaultTableModel(null, columnNames);
            
            Connection connection = null;
            DatabaseConnection dbConnection = new DatabaseConnection();
            // Obtener la conexión desde DataBaseConnection
            connection = dbConnection.getConnection();
            PeliculaDAO peliculaDAO = new PeliculaDAO(connection);
            PeliculaController pelisControl = new PeliculaController(peliculaDAO);
            
            List<Pelicula> listaPelicula = pelisControl.obtenerPeliculas();
            for ( Pelicula peli: listaPelicula){
                Object[] data = new Object[columnNames.length];
                data[0] = peli.getId();
                data[1] = peli.getTitulo();
                data[2] = peli.getDuracion();
                data[3] = peli.getDistribuidor();
                data[4] = peli.getClasificacion();
                data[5] = peli.getDirector();
                data[6] = peli.getPais();
                data[7] = peli.getDescripcion();
                
                model.addRow(data);
                
            }
            jTpelis.setModel(model);
            
        } catch (SQLException ex) {
            Logger.getLogger(AgregarFuncion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        
        
        
    }

    
    public void actualizarVentana() {
        // Revalida y repinta para reflejar los cambios
        DefaultTableModel modelo = (DefaultTableModel) jTpelis.getModel();
        modelo.setRowCount(0);  // Esto limpia todas las filas en la tabla 
        cargarPeliculas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTpelis = new javax.swing.JTable();
        jBeliminar = new javax.swing.JButton();
        jBact = new javax.swing.JButton();
        jBvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar Pelicula");

        jTpelis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTpelis);

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBact.setText("Actualizar");
        jBact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactActionPerformed(evt);
            }
        });

        jBvolver.setText("Volver");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBvolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBeliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBeliminar)
                    .addComponent(jBact)
                    .addComponent(jBvolver))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
int selectedRow = jTpelis.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una película.");
        return;
    }

    int peliculaId = (int) jTpelis.getValueAt(selectedRow, 0); // ID de la película
    
    try {
        Connection connection = new DatabaseConnection().getConnection();
        PeliculaDAO peliculaDAO = new PeliculaDAO(connection);
        
                peliculaDAO.eliminarPelicula(peliculaId);
                      actualizarVentana();
        JOptionPane.showMessageDialog(this, "Función eliminada exitosamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar función: " + e.getMessage());
    }
        
     
      
        
        
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactActionPerformed
int selectedRow = jTpelis.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una película.");
        return;
    }
     int peliculaId = (int) jTpelis.getValueAt(selectedRow, 0); // ID de la película
     
   
        try {
        Connection connection = new DatabaseConnection().getConnection();
        PeliculaDAO peliculaDAO = new PeliculaDAO(connection);
        Pelicula pelicula = new Pelicula();
        // Obtener los datos de la fila seleccionada
        pelicula.setId((Integer) jTpelis.getValueAt(selectedRow, 0));
        pelicula.setTitulo((String) jTpelis.getValueAt(selectedRow, 1));
        pelicula.setDuracion((int) jTpelis.getValueAt(selectedRow, 2));
        pelicula.setDistribuidor((String) jTpelis.getValueAt(selectedRow, 3));
        pelicula.setClasificacion((String) jTpelis.getValueAt(selectedRow, 4));
        pelicula.setDirector((String) jTpelis.getValueAt(selectedRow, 5));
        pelicula.setPais((String) jTpelis.getValueAt(selectedRow, 6));
        pelicula.setDescripcion((String) jTpelis.getValueAt(selectedRow, 7));
            System.out.println(pelicula);
        // Actualizar película en la base de datos
        peliculaDAO.actualizarPelicula(pelicula);
        
        // Actualizar la ventana o tabla
        actualizarVentana(); // Aquí deberías recargar los datos de la tabla para que se refleje la actualización
        
        
        JOptionPane.showMessageDialog(this, "Funciones actualizadas exitosamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar las funciones: " + e.getMessage());
    }
        
     
        
    }//GEN-LAST:event_jBactActionPerformed

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
         dispose();
        MenuProgramacion menu = new MenuProgramacion();
        menu.setVisible(true);
    }//GEN-LAST:event_jBvolverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBact;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTpelis;
    // End of variables declaration//GEN-END:variables
}
