/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import uam.azc.adsi.cinetubi.controller.PeliculaController;
import uam.azc.adsi.cinetubi.dao.PeliculaDAOJony;
import uam.azc.adsi.cinetubi.util.DatabaseConnection;

/**
 *
 * @author Jony
 */
public class MenuProgramacion extends javax.swing.JFrame {

    /**
     * Creates new form MenuProgramacion
     */
    public MenuProgramacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBagregarP = new javax.swing.JButton();
        jBeditarC = new javax.swing.JButton();
        jBprogE = new javax.swing.JButton();
        jBvolver = new javax.swing.JButton();
        jBpelicula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBagregarP.setText("Agregar Pelicula");
        jBagregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarPActionPerformed(evt);
            }
        });

        jBeditarC.setText("Añadir Función");
        jBeditarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarCActionPerformed(evt);
            }
        });

        jBprogE.setText("Editar Cartelera");
        jBprogE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprogEActionPerformed(evt);
            }
        });

        jBvolver.setText("Volver");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jBpelicula.setText("Editar Pelicula");
        jBpelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jBvolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBagregarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBeditarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBprogE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBpelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jBagregarP)
                .addGap(18, 18, 18)
                .addComponent(jBeditarC)
                .addGap(16, 16, 16)
                .addComponent(jBpelicula)
                .addGap(18, 18, 18)
                .addComponent(jBprogE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jBvolver)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarPActionPerformed
     
        try {
            dispose();
            Connection connection = null;
            DatabaseConnection dbConnection = DatabaseConnection.getInstance();
            // Obtener la conexión desde DataBaseConnection
            connection = dbConnection.getConnection();
            // Instanciar el DAO y el controlador
            PeliculaDAOJony peliculaDAO = new PeliculaDAOJony(connection);
            PeliculaController peliculaController = new PeliculaController(peliculaDAO);
            AgregarPeliculaVista view = new AgregarPeliculaVista(peliculaController);
            view.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuProgramacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBagregarPActionPerformed

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed

       
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBeditarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarCActionPerformed

        AgregarFuncionJony edit = new AgregarFuncionJony();
        edit.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jBeditarCActionPerformed

    private void jBpeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpeliculaActionPerformed
        
        EditarPelicula edit = new EditarPelicula();
        edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBpeliculaActionPerformed

    private void jBprogEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprogEActionPerformed
        EditarCartelera edit = new EditarCartelera();
        edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBprogEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarP;
    private javax.swing.JButton jBeditarC;
    private javax.swing.JButton jBpelicula;
    private javax.swing.JButton jBprogE;
    private javax.swing.JButton jBvolver;
    // End of variables declaration//GEN-END:variables
}
