/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import uam.azc.adsi.cinetubi.controller.DulceriaController;

/**
 *
 * @author aldai
 */
public class MenuView extends javax.swing.JFrame {

  private DulceriaController dulceriaController;

  /**
   * Creates new form MenuView
   *
   * @param dulceriaController
   */
  public MenuView(DulceriaController dulceriaController) {
    initComponents();
    this.dulceriaController = dulceriaController;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TaquillaButton = new javax.swing.JButton();
    DulceriaButton = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Menu");

    TaquillaButton.setText("Taquilla");
    TaquillaButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TaquillaButtonActionPerformed(evt);
      }
    });

    DulceriaButton.setText("Dulceria");
    DulceriaButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DulceriaButtonActionPerformed(evt);
      }
    });

    jButton3.setText("Programar Funcion");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(142, 142, 142)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(DulceriaButton)
              .addComponent(TaquillaButton)))
          .addGroup(layout.createSequentialGroup()
            .addGap(113, 113, 113)
            .addComponent(jButton3)))
        .addContainerGap(151, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addComponent(TaquillaButton)
        .addGap(18, 18, 18)
        .addComponent(DulceriaButton)
        .addGap(18, 18, 18)
        .addComponent(jButton3)
        .addContainerGap(113, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void DulceriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DulceriaButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_DulceriaButtonActionPerformed

  private void TaquillaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaquillaButtonActionPerformed
    VentaDulceriaView dulceriaView = new VentaDulceriaView(dulceriaController);
    dulceriaView.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_TaquillaButtonActionPerformed

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new MenuView().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton DulceriaButton;
  private javax.swing.JButton TaquillaButton;
  private javax.swing.JButton jButton3;
  // End of variables declaration//GEN-END:variables
}
