/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import uam.azc.adsi.cinetubi.controller.DulceriaController;
import uam.azc.adsi.cinetubi.exceptions.ProductNotFoundException;

/**
 *
 * @author aldai
 */
public class SingleProductPanel extends javax.swing.JPanel {

  private int productId;

  private String name;
  private BigDecimal price;
  private DulceriaController dulceriaController;

  /**
   * Creates new form SnackCard
   *
   * @param dulceriaController
   * @param productId
   * @param price
   * @param name
   */
  public SingleProductPanel(int productId, String name, BigDecimal price, DulceriaController dulceriaController) {
    this.productId = productId;
    this.name = name;
    this.price = price;
    this.dulceriaController = dulceriaController;
    initComponents();
    initCardContent();
  }

  private void initCardContent() {
    productPriceLabel.setText(dulceriaController.getFormatter().format(price));
    productTitle.setText(name);
//    productIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcornSmall.png")));
  }

  public void scaleImage() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    productTitle = new javax.swing.JLabel();
    productIcon = new javax.swing.JLabel();
    qtyLabel = new javax.swing.JLabel();
    decreaseQtyButton = new javax.swing.JButton();
    increaseQtyButton = new javax.swing.JButton();
    productPriceLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(204, 255, 204));

    productTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productTitle.setText("Palomitas Chicas");
    productTitle.setOpaque(true);

    productIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productIcon.setText("ALT TEXT");

    qtyLabel.setText("0");

    decreaseQtyButton.setText("-");
    decreaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQtyButtonActionPerformed(evt);
      }
    });

    increaseQtyButton.setText("+");
    increaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQtyButtonActionPerformed(evt);
      }
    });

    productPriceLabel.setText("$100.00");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(productTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
              .addComponent(productIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(decreaseQtyButton)
                .addGap(11, 11, 11)
                .addComponent(qtyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(increaseQtyButton))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(productPriceLabel)
                .addGap(20, 20, 20)))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(productTitle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(qtyLabel)
          .addComponent(decreaseQtyButton)
          .addComponent(increaseQtyButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(16, 16, 16))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQtyButtonActionPerformed
    try {
      dulceriaController.decreaseProductQuantity(productId, evt);
    } catch (ProductNotFoundException ex) {
      Logger.getLogger(SingleProductPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_decreaseQtyButtonActionPerformed

  private void increaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQtyButtonActionPerformed
    try {
      dulceriaController.increaseProductQuantity(productId, evt);
    } catch (ProductNotFoundException ex) {
      Logger.getLogger(SingleProductPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_increaseQtyButtonActionPerformed

  public JLabel getQtyLabel() {
    return qtyLabel;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton decreaseQtyButton;
  private javax.swing.JButton increaseQtyButton;
  private javax.swing.JLabel productIcon;
  private javax.swing.JLabel productPriceLabel;
  private javax.swing.JLabel productTitle;
  private javax.swing.JLabel qtyLabel;
  // End of variables declaration//GEN-END:variables
}
