/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author aldai
 */
public class SingleProductPanel extends javax.swing.JPanel {

  private NumberFormat formatter;
  private int id;
  private String name;
  private BigDecimal price;
  
  /**
   * Creates new form SnackCard
   *
   * @param id
   * @param price
   * @param name
   */
  public SingleProductPanel(int id, String name, BigDecimal price) {
    formatter = NumberFormat.getCurrencyInstance(Locale.US);
    this.id = id;
    this.name = name;
    this.price = price;
    initComponents();
    initCardContent();
  }

  private void initCardContent() {
    productPriceLabel.setText(formatter.format(price));
    productTitle.setText(name);
//    productIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcornSmall.png")));
  }

  public void scaleImage() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    productTitle = new javax.swing.JLabel();
    productIcon = new javax.swing.JLabel();
    productControlsPanel = new javax.swing.JPanel();
    decreaseQtyButton = new javax.swing.JButton();
    qtyLabel = new javax.swing.JLabel();
    increaseQtyButton = new javax.swing.JButton();
    productPriceLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(204, 255, 204));

    productTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productTitle.setText("Palomitas Chicas");
    productTitle.setOpaque(true);

    productIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productIcon.setText("ALT TEXT");

    productControlsPanel.setOpaque(false);

    decreaseQtyButton.setText("-");
    decreaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQtyButtonActionPerformed(evt);
      }
    });

    qtyLabel.setText("0");

    increaseQtyButton.setText("+");
    increaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQtyButtonActionPerformed(evt);
      }
    });

    productPriceLabel.setText("$100.00");

    javax.swing.GroupLayout productControlsPanelLayout = new javax.swing.GroupLayout(productControlsPanel);
    productControlsPanel.setLayout(productControlsPanelLayout);
    productControlsPanelLayout.setHorizontalGroup(
      productControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(productControlsPanelLayout.createSequentialGroup()
        .addContainerGap(36, Short.MAX_VALUE)
        .addGroup(productControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productControlsPanelLayout.createSequentialGroup()
            .addComponent(decreaseQtyButton)
            .addGap(11, 11, 11)
            .addComponent(qtyLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(increaseQtyButton)
            .addGap(28, 28, 28))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productControlsPanelLayout.createSequentialGroup()
            .addComponent(productPriceLabel)
            .addGap(48, 48, 48))))
    );
    productControlsPanelLayout.setVerticalGroup(
      productControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(productControlsPanelLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(productControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(qtyLabel)
          .addComponent(decreaseQtyButton)
          .addComponent(increaseQtyButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(productTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(productIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(productControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(productTitle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQtyButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_decreaseQtyButtonActionPerformed

  private void increaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQtyButtonActionPerformed

  }//GEN-LAST:event_increaseQtyButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton decreaseQtyButton;
  private javax.swing.JButton increaseQtyButton;
  private javax.swing.JPanel productControlsPanel;
  private javax.swing.JLabel productIcon;
  private javax.swing.JLabel productPriceLabel;
  private javax.swing.JLabel productTitle;
  private javax.swing.JLabel qtyLabel;
  // End of variables declaration//GEN-END:variables
}
