/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.Image;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uam.azc.adsi.cinetubi.controller.DulceriaController;
import uam.azc.adsi.cinetubi.exceptions.ProductNotFoundException;

/**
 *
 * @author aldai
 */
public class SingleProductPanel extends javax.swing.JPanel {

  private int productId;

  private String name;
  private BigDecimal price;
  private DulceriaController dulceriaController;

  /**
   * Creates new form SnackCard
   *
   * @param dulceriaController
   * @param productId
   * @param price
   * @param name
   */
  public SingleProductPanel(int productId, String name, BigDecimal price, DulceriaController dulceriaController) {
    this.productId = productId;
    this.name = name;
    this.price = price;
    this.dulceriaController = dulceriaController;
    initComponents();
    initCardContent();
  }

  private void initCardContent() {
    productTitle.setText("<html>"
            + name
            + "<br>"
            + name
            + "</html>");
    productPriceLabel.setText(dulceriaController.getFormatter().format(price));

    ImageIcon icon = new ImageIcon(getClass().getResource("/images/popcornSmall.png"));
    Image scaledImage = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledImage);
    productIcon.setIcon(scaledIcon);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    productTitle = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    productIcon = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    decreaseQtyButton = new javax.swing.JButton();
    qtyLabel = new javax.swing.JLabel();
    increaseQtyButton = new javax.swing.JButton();
    productPriceLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(204, 255, 204));
    setBorder(javax.swing.BorderFactory.createEtchedBorder());
    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

    jPanel1.setOpaque(false);

    productTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    productTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productTitle.setText("<html>Palomitas<br> Chicas</html>");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 193, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap(50, Short.MAX_VALUE)
          .addComponent(productTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(50, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 83, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(productTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
          .addContainerGap()))
    );

    add(jPanel1);

    jPanel2.setOpaque(false);

    productIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcornSmall.png"))); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    add(jPanel2);

    jPanel3.setOpaque(false);

    decreaseQtyButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    decreaseQtyButton.setText("-");
    decreaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQtyButtonActionPerformed(evt);
      }
    });

    qtyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    qtyLabel.setText("0");

    increaseQtyButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    increaseQtyButton.setText("+");
    increaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQtyButtonActionPerformed(evt);
      }
    });

    productPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    productPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    productPriceLabel.setText("$100.00");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap(36, Short.MAX_VALUE)
        .addComponent(decreaseQtyButton)
        .addGap(18, 18, 18)
        .addComponent(qtyLabel)
        .addGap(20, 20, 20)
        .addComponent(increaseQtyButton)
        .addContainerGap(37, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(productPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(increaseQtyButton)
          .addComponent(qtyLabel)
          .addComponent(decreaseQtyButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(productPriceLabel)
        .addContainerGap())
    );

    add(jPanel3);
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQtyButtonActionPerformed
    try {
      dulceriaController.decreaseProductQuantity(productId, evt);
    } catch (ProductNotFoundException ex) {
      Logger.getLogger(SingleProductPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_decreaseQtyButtonActionPerformed

  private void increaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQtyButtonActionPerformed
    try {
      dulceriaController.increaseProductQuantity(productId, evt);
    } catch (ProductNotFoundException ex) {
      Logger.getLogger(SingleProductPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_increaseQtyButtonActionPerformed

  public JLabel getQtyLabel() {
    return qtyLabel;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton decreaseQtyButton;
  private javax.swing.JButton increaseQtyButton;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel productIcon;
  private javax.swing.JLabel productPriceLabel;
  private javax.swing.JLabel productTitle;
  private javax.swing.JLabel qtyLabel;
  // End of variables declaration//GEN-END:variables
}
