/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uam.azc.adsi.cinetubi.modelo.Snack;

/**
 *
 * @author aldai
 */
public class SnackCard extends javax.swing.JPanel {

  /**
   * Creates new form SnackCard
   * @param s instance of Snack 
   */
  public SnackCard(Snack s) {
    initComponents();
    initCardContent(s);
  }
  
  private void initCardContent(Snack s){
    snackNombre.setText(s.getNombre());
    NumberFormat formatter = NumberFormat.getCurrencyInstance(Locale.US);
    snackPrice.setText(formatter.format(s.getPrecio()));
  };

  
  public void scaleImage(){
    ImageIcon icon = new ImageIcon("graphics/popcornSmall.png");
    snackIcon.setIcon(icon);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    snackNombre = new javax.swing.JLabel();
    snackIcon = new javax.swing.JLabel();
    decreaseQuantButton = new javax.swing.JButton();
    increaseQuantButton = new javax.swing.JButton();
    currentQuant = new javax.swing.JLabel();
    snackPrice = new javax.swing.JLabel();

    snackNombre.setText("Palomitas Chicas");

    snackIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/cinetubi/view/graphics/popcornSmall.png"))); // NOI18N

    decreaseQuantButton.setText("-");
    decreaseQuantButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQuantButtonActionPerformed(evt);
      }
    });

    increaseQuantButton.setText("+");
    increaseQuantButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQuantButtonActionPerformed(evt);
      }
    });

    currentQuant.setText("0");

    snackPrice.setText("$100.00");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(snackNombre)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(snackIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(decreaseQuantButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(currentQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(increaseQuantButton)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(snackPrice)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(snackNombre)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(snackIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(decreaseQuantButton)
          .addComponent(increaseQuantButton)
          .addComponent(currentQuant))
        .addGap(18, 18, 18)
        .addComponent(snackPrice)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQuantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQuantButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_decreaseQuantButtonActionPerformed

  private void increaseQuantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQuantButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_increaseQuantButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel currentQuant;
  private javax.swing.JButton decreaseQuantButton;
  private javax.swing.JButton increaseQuantButton;
  private javax.swing.JLabel snackIcon;
  private javax.swing.JLabel snackNombre;
  private javax.swing.JLabel snackPrice;
  // End of variables declaration//GEN-END:variables
}
