/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uam.azc.adsi.cinetubi.model.Snack;

/**
 *
 * @author aldai
 */
public class SnackPanel extends javax.swing.JPanel {

  /**
   * Creates new form SnackCard
   * @param s instance of Snack 
   */
  public SnackPanel(Snack s) {
    initComponents();
    initCardContent(s);
  }
  
  private void initCardContent(Snack s){
    snackNombreLabel.setText(s.getNombre());
    NumberFormat formatter = NumberFormat.getCurrencyInstance(Locale.US);
    snackPriceLabel.setText(formatter.format(s.getPrecio()));
  };

  
  public void scaleImage(){
    
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    snackNombreLabel = new javax.swing.JLabel();
    decreaseQtyButton = new javax.swing.JButton();
    increaseQtyButton = new javax.swing.JButton();
    qtyLabel = new javax.swing.JLabel();
    snackPriceLabel = new javax.swing.JLabel();
    altTextLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 102));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    snackNombreLabel.setText("Palomitas Chicas");
    add(snackNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    decreaseQtyButton.setText("-");
    decreaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQtyButtonActionPerformed(evt);
      }
    });
    add(decreaseQtyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 134, -1, -1));

    increaseQtyButton.setText("+");
    increaseQtyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQtyButtonActionPerformed(evt);
      }
    });
    add(increaseQtyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 134, -1, -1));

    qtyLabel.setText("0");
    add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 139, 9, -1));

    snackPriceLabel.setText("$100.00");
    add(snackPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 179, -1, -1));

    altTextLabel.setBackground(new java.awt.Color(255, 0, 51));
    altTextLabel.setText("THIS SHOULD BE AN IMAGE");
    add(altTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 70));
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQtyButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_decreaseQtyButtonActionPerformed

  private void increaseQtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQtyButtonActionPerformed
    
  }//GEN-LAST:event_increaseQtyButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel altTextLabel;
  private javax.swing.JButton decreaseQtyButton;
  private javax.swing.JButton increaseQtyButton;
  private javax.swing.JLabel qtyLabel;
  private javax.swing.JLabel snackNombreLabel;
  private javax.swing.JLabel snackPriceLabel;
  // End of variables declaration//GEN-END:variables
}
