/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uam.azc.adsi.cinetubi.model.Snack;

/**
 *
 * @author aldai
 */
public class SnackPanel extends javax.swing.JPanel {

  /**
   * Creates new form SnackCard
   * @param s instance of Snack 
   */
  public SnackPanel(Snack s) {
    initComponents();
    initCardContent(s);
  }
  
  private void initCardContent(Snack s){
    snackNombre.setText(s.getNombre());
    NumberFormat formatter = NumberFormat.getCurrencyInstance(Locale.US);
    snackPrice.setText(formatter.format(s.getPrecio()));
  };

  
  public void scaleImage(){
    
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    snackNombre = new javax.swing.JLabel();
    decreaseQuantButton = new javax.swing.JButton();
    increaseQuantButton = new javax.swing.JButton();
    currentQuant = new javax.swing.JLabel();
    snackPrice = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 102));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    snackNombre.setText("Palomitas Chicas");
    add(snackNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    decreaseQuantButton.setText("-");
    decreaseQuantButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decreaseQuantButtonActionPerformed(evt);
      }
    });
    add(decreaseQuantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 134, -1, -1));

    increaseQuantButton.setText("+");
    increaseQuantButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        increaseQuantButtonActionPerformed(evt);
      }
    });
    add(increaseQuantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 134, -1, -1));

    currentQuant.setText("0");
    add(currentQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 139, 9, -1));

    snackPrice.setText("$100.00");
    add(snackPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 179, -1, -1));

    jLabel1.setBackground(new java.awt.Color(255, 0, 51));
    jLabel1.setText("THIS SHOULD BE AN IMAGE");
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 70));
  }// </editor-fold>//GEN-END:initComponents

  private void decreaseQuantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQuantButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_decreaseQuantButtonActionPerformed

  private void increaseQuantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQuantButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_increaseQuantButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel currentQuant;
  private javax.swing.JButton decreaseQuantButton;
  private javax.swing.JButton increaseQuantButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel snackNombre;
  private javax.swing.JLabel snackPrice;
  // End of variables declaration//GEN-END:variables
}
