/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import javax.swing.BoxLayout;

/**
 *
 * @author José Vicente López López 2212002118
 */
public class Taquilla extends javax.swing.JFrame {

    /**
     * Creates new form Taquilla
     */
    public Taquilla() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlFunciones = new javax.swing.JPanel();
        pnlAsientos = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        txtAsientos = new javax.swing.JTextField();
        lblTituloAsientos = new javax.swing.JLabel();
        pnlResumen = new javax.swing.JPanel();
        lblRBoletos = new javax.swing.JLabel();
        lblRPelicula = new javax.swing.JLabel();
        lblRHorario = new javax.swing.JLabel();
        lblRIdioma = new javax.swing.JLabel();
        lblRTotal = new javax.swing.JLabel();
        lblRPrecio = new javax.swing.JLabel();
        lblRAsientos = new javax.swing.JLabel();
        lblRSala = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblAux1 = new javax.swing.JLabel();
        lblTaqulla = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        scrollDescripcion = new javax.swing.JScrollPane();
        pnlDescripcion = new javax.swing.JPanel();
        lblPelicula = new javax.swing.JLabel();
        lblPClasificacion = new javax.swing.JLabel();
        lblPDireccion = new javax.swing.JLabel();
        lblPDuracion = new javax.swing.JLabel();
        lblPDistribuidora = new javax.swing.JLabel();
        lblPDescripcion = new javax.swing.JLabel();
        lblPGenero = new javax.swing.JLabel();
        txtPelicula = new javax.swing.JTextField();
        txtPClasificacion = new javax.swing.JTextField();
        txtPGenero = new javax.swing.JTextField();
        txtPDirector = new javax.swing.JTextField();
        txtPDuracion = new javax.swing.JTextField();
        txtPDistribuidora = new javax.swing.JTextField();
        txtPDescripcion = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de Boletos");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 102, 102));
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(0, 102, 102));

        pnlFunciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlFunciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        pnlFunciones.setName(""); // NOI18N
        pnlFunciones.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout pnlFuncionesLayout = new javax.swing.GroupLayout(pnlFunciones);
        pnlFunciones.setLayout(pnlFuncionesLayout);
        pnlFuncionesLayout.setHorizontalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlFuncionesLayout.setVerticalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlAsientos.setBackground(new java.awt.Color(255, 255, 255));
        pnlAsientos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        lbl1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 102, 102));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("1");

        lbl2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 102, 102));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("2");

        lbl3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 102, 102));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("3");

        lbl4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 102, 102));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("4");

        lbl5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 102, 102));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("5");

        lbl6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 102, 102));
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("6");

        lbl7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 102, 102));
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("7");

        lbl8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 102, 102));
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("8");

        lbl9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 102, 102));
        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setText("9");

        lbl10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 102, 102));
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("10");

        lbl11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 102, 102));
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("11");

        lbl12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 102, 102));
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setText("12");

        lbl13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl13.setForeground(new java.awt.Color(0, 102, 102));
        lbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl13.setText("13");

        lbl14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl14.setForeground(new java.awt.Color(0, 102, 102));
        lbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl14.setText("14");

        lbl15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl15.setForeground(new java.awt.Color(0, 102, 102));
        lbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl15.setText("15");

        lbl16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl16.setForeground(new java.awt.Color(0, 102, 102));
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl16.setText("16");

        lbl17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl17.setForeground(new java.awt.Color(0, 102, 102));
        lbl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl17.setText("17");

        lbl18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl18.setForeground(new java.awt.Color(0, 102, 102));
        lbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl18.setText("18");

        lbl19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl19.setForeground(new java.awt.Color(0, 102, 102));
        lbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl19.setText("19");

        lbl20.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl20.setForeground(new java.awt.Color(0, 102, 102));
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setText("20");

        lbl21.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl21.setForeground(new java.awt.Color(0, 102, 102));
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setText("21");

        lbl22.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl22.setForeground(new java.awt.Color(0, 102, 102));
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setText("22");

        lbl23.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl23.setForeground(new java.awt.Color(0, 102, 102));
        lbl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl23.setText("23");

        lbl24.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl24.setForeground(new java.awt.Color(0, 102, 102));
        lbl24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl24.setText("24");

        lbl25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl25.setForeground(new java.awt.Color(0, 102, 102));
        lbl25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl25.setText("25");

        lbl26.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl26.setForeground(new java.awt.Color(0, 102, 102));
        lbl26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl26.setText("26");

        lbl27.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl27.setForeground(new java.awt.Color(0, 102, 102));
        lbl27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl27.setText("27");

        lbl28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl28.setForeground(new java.awt.Color(0, 102, 102));
        lbl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl28.setText("28");

        lbl29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl29.setForeground(new java.awt.Color(0, 102, 102));
        lbl29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl29.setText("29");

        lbl30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl30.setForeground(new java.awt.Color(0, 102, 102));
        lbl30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl30.setText("30");

        lblAsientos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(0, 102, 102));
        lblAsientos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAsientos.setText("Seleccionar Asientos:");

        txtAsientos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtAsientos.setForeground(new java.awt.Color(0, 102, 102));

        lblTituloAsientos.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTituloAsientos.setForeground(new java.awt.Color(0, 102, 102));
        lblTituloAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAsientos.setText("Seleccionar Asietos");

        javax.swing.GroupLayout pnlAsientosLayout = new javax.swing.GroupLayout(pnlAsientos);
        pnlAsientos.setLayout(pnlAsientosLayout);
        pnlAsientosLayout.setHorizontalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                                        .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                                        .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlAsientosLayout.createSequentialGroup()
                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlAsientosLayout.createSequentialGroup()
                                .addComponent(lblAsientos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addComponent(lblTituloAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAsientosLayout.setVerticalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addComponent(lbl5)
                    .addComponent(lbl6)
                    .addComponent(lbl7)
                    .addComponent(lbl8)
                    .addComponent(lbl9)
                    .addComponent(lbl10))
                .addGap(18, 18, 18)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl11)
                    .addComponent(lbl12)
                    .addComponent(lbl13)
                    .addComponent(lbl14)
                    .addComponent(lbl15)
                    .addComponent(lbl16)
                    .addComponent(lbl17)
                    .addComponent(lbl18)
                    .addComponent(lbl19)
                    .addComponent(lbl20))
                .addGap(18, 18, 18)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl21)
                    .addComponent(lbl22)
                    .addComponent(lbl23)
                    .addComponent(lbl24)
                    .addComponent(lbl25)
                    .addComponent(lbl26)
                    .addComponent(lbl27)
                    .addComponent(lbl28)
                    .addComponent(lbl29)
                    .addComponent(lbl30))
                .addGap(18, 18, 18)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlResumen.setBackground(new java.awt.Color(255, 255, 255));
        pnlResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        lblRBoletos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRBoletos.setForeground(new java.awt.Color(0, 102, 102));
        lblRBoletos.setText("Boletos: ");

        lblRPelicula.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRPelicula.setForeground(new java.awt.Color(0, 102, 102));
        lblRPelicula.setText("Pelicula: ");

        lblRHorario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRHorario.setForeground(new java.awt.Color(0, 102, 102));
        lblRHorario.setText("Horario: ");

        lblRIdioma.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRIdioma.setForeground(new java.awt.Color(0, 102, 102));
        lblRIdioma.setText("Idioma:");

        lblRTotal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRTotal.setForeground(new java.awt.Color(0, 102, 102));
        lblRTotal.setText("Subtotal: ");

        lblRPrecio.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRPrecio.setForeground(new java.awt.Color(0, 102, 102));
        lblRPrecio.setText("Precio P/B:");

        lblRAsientos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRAsientos.setForeground(new java.awt.Color(0, 102, 102));
        lblRAsientos.setText("Asintos: ");

        lblRSala.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRSala.setForeground(new java.awt.Color(0, 102, 102));
        lblRSala.setText("Sala: ");

        javax.swing.GroupLayout pnlResumenLayout = new javax.swing.GroupLayout(pnlResumen);
        pnlResumen.setLayout(pnlResumenLayout);
        pnlResumenLayout.setHorizontalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRPelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblRHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblRIdioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblRSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRAsientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblRPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(lblRTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlResumenLayout.setVerticalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRBoletos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRIdioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRAsientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRTotal)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Taquilla");

        lblMenu.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblAux1.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblAux1.setForeground(new java.awt.Color(255, 255, 255));
        lblAux1.setText("→");

        lblTaqulla.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblTaqulla.setForeground(new java.awt.Color(255, 255, 255));
        lblTaqulla.setText("Taquilla");
        lblTaqulla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTaqullaMousePressed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        scrollDescripcion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDescripcion.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        pnlDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        pnlDescripcion.setAutoscrolls(true);
        pnlDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDescripcion.setFocusTraversalPolicyProvider(true);
        pnlDescripcion.setPreferredSize(new java.awt.Dimension(200, 100));

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(0, 102, 102));
        lblPelicula.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPelicula.setText("Titulo:");

        lblPClasificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPClasificacion.setForeground(new java.awt.Color(0, 102, 102));
        lblPClasificacion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPClasificacion.setText("Clasificación:");

        lblPDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPDireccion.setForeground(new java.awt.Color(0, 102, 102));
        lblPDireccion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPDireccion.setText("Director:");

        lblPDuracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPDuracion.setForeground(new java.awt.Color(0, 102, 102));
        lblPDuracion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPDuracion.setText("Duracion:");

        lblPDistribuidora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPDistribuidora.setForeground(new java.awt.Color(0, 102, 102));
        lblPDistribuidora.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPDistribuidora.setText("Distribuidora:");

        lblPDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPDescripcion.setForeground(new java.awt.Color(0, 102, 102));
        lblPDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPDescripcion.setText("Descripción:");

        lblPGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPGenero.setForeground(new java.awt.Color(0, 102, 102));
        lblPGenero.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPGenero.setText("Genero:");

        txtPelicula.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPelicula.setForeground(new java.awt.Color(0, 102, 102));

        txtPClasificacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPClasificacion.setForeground(new java.awt.Color(0, 102, 102));

        txtPGenero.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPGenero.setForeground(new java.awt.Color(0, 102, 102));

        txtPDirector.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPDirector.setForeground(new java.awt.Color(0, 102, 102));

        txtPDuracion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPDuracion.setForeground(new java.awt.Color(0, 102, 102));

        txtPDistribuidora.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPDistribuidora.setForeground(new java.awt.Color(0, 102, 102));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        txtPDescripcion.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlDescripcionLayout = new javax.swing.GroupLayout(pnlDescripcion);
        pnlDescripcion.setLayout(pnlDescripcionLayout);
        pnlDescripcionLayout.setHorizontalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDescripcionLayout.createSequentialGroup()
                        .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPDistribuidora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPClasificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPDirector)
                    .addComponent(txtPelicula)
                    .addComponent(txtPClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtPGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtPDuracion)
                    .addComponent(txtPDistribuidora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPDescripcion))
                .addContainerGap())
        );
        pnlDescripcionLayout.setVerticalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula)
                    .addComponent(txtPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPClasificacion)
                    .addComponent(txtPClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPGenero)
                    .addComponent(txtPGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPDistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPDistribuidora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDescripcionLayout.createSequentialGroup()
                        .addComponent(lblPDescripcion)
                        .addContainerGap())
                    .addComponent(txtPDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        scrollDescripcion.setViewportView(pnlDescripcion);

        btnPagar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(0, 102, 102));
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFunciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPagar))
                                .addComponent(pnlResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAux1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTaqulla)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAux1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTaqulla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(scrollDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagar)))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Taquilla taquilla=new Taquilla();
        taquilla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        // TODO add your handling code here:
        Menu menu=new Menu(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblTaqullaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaqullaMousePressed
        // TODO add your handling code here:
        Taquilla taquilla=new Taquilla();
        taquilla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblTaqullaMousePressed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        ProcesarVenta venta=new ProcesarVenta();
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taquilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblAux1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblPClasificacion;
    private javax.swing.JLabel lblPDescripcion;
    private javax.swing.JLabel lblPDireccion;
    private javax.swing.JLabel lblPDistribuidora;
    private javax.swing.JLabel lblPDuracion;
    private javax.swing.JLabel lblPGenero;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblRAsientos;
    private javax.swing.JLabel lblRBoletos;
    private javax.swing.JLabel lblRHorario;
    private javax.swing.JLabel lblRIdioma;
    private javax.swing.JLabel lblRPelicula;
    private javax.swing.JLabel lblRPrecio;
    private javax.swing.JLabel lblRSala;
    private javax.swing.JLabel lblRTotal;
    private javax.swing.JLabel lblTaqulla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAsientos;
    private javax.swing.JPanel pnlAsientos;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFunciones;
    private javax.swing.JPanel pnlResumen;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextField txtAsientos;
    private javax.swing.JTextField txtPClasificacion;
    private javax.swing.JScrollPane txtPDescripcion;
    private javax.swing.JTextField txtPDirector;
    private javax.swing.JTextField txtPDistribuidora;
    private javax.swing.JTextField txtPDuracion;
    private javax.swing.JTextField txtPGenero;
    private javax.swing.JTextField txtPelicula;
    // End of variables declaration//GEN-END:variables

    void bloquearTxT(){
        txtPClasificacion.setEditable(false);
        txtPDescripcion.setEnabled(false);
        txtPDirector.setEditable(false);
        txtPDistribuidora.setEditable(false);
        txtPDuracion.setEditable(false);
        txtPGenero.setEditable(false);
        txtPelicula.setEditable(false);
    }


}
