/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.math.BigDecimal;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import uam.azc.adsi.cinetubi.controller.DulceriaController;

/**
 *
 * @author aldai
 */
public class VentaDulceriaView extends javax.swing.JFrame {

  private DulceriaController dulceriaController;

  /**
   * Creates new form VentaDulceriaView
   *
   * @param dCon
   */
  public VentaDulceriaView(DulceriaController dCon) {
    this.dulceriaController = dCon;
    initComponents();
    this.setContentPane(buildContentPane());
  }

  private JPanel buildContentPane() {
    JPanel panel = new JPanel(new BorderLayout());

    int totalItems = dulceriaController.getSnackCatalog().getCatalog().size();
    
    int gridColumns = 3;
    int gridRows = totalItems / gridColumns;
    System.out.println("totalItmes: " + totalItems + " gridCOlums: " + gridColumns + " gridRows: " + gridRows);

    gridPanelItems.setLayout(new GridLayout(gridRows, gridColumns, 20, 18));
    for (SnackPanel sp : dulceriaController.createSnackPanels()) {
      gridPanelItems.add(sp);
    }

    scrollPaneItems.setViewportView(gridPanelItems);
    scrollPaneItems.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    scrollPaneItems.setPreferredSize(new Dimension(400, 200));
    scrollPaneItems.getVerticalScrollBar().setUnitIncrement(16);

    panel.add(scrollPaneItems, BorderLayout.CENTER);
    return panel;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPaneItems = new javax.swing.JScrollPane();
    gridPanelItems = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Dulceria");

    javax.swing.GroupLayout gridPanelItemsLayout = new javax.swing.GroupLayout(gridPanelItems);
    gridPanelItems.setLayout(gridPanelItemsLayout);
    gridPanelItemsLayout.setHorizontalGroup(
      gridPanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 210, Short.MAX_VALUE)
    );
    gridPanelItemsLayout.setVerticalGroup(
      gridPanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 160, Short.MAX_VALUE)
    );

    scrollPaneItems.setViewportView(gridPanelItems);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(195, 195, 195)
        .addComponent(scrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(133, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(127, 127, 127)
        .addComponent(scrollPaneItems, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(76, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(VentaDulceriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(VentaDulceriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(VentaDulceriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(VentaDulceriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new VentaDulceriaView().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel gridPanelItems;
  private javax.swing.JScrollPane scrollPaneItems;
  // End of variables declaration//GEN-END:variables
}
