/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.azc.adsi.cinetubi.view;

import java.awt.Color;
import javax.swing.JTextArea;
import uam.azc.adsi.cinetubi.controller.TaquillaController;
import uam.azc.adsi.cinetubi.controller.VentaController;
import uam.azc.adsi.cinetubi.dao.BoletoDAO;

/**
 *
 * @author vicen
 */
public class VentaBoletos extends javax.swing.JFrame {
    private String modo="efectivo";
    private final TaquillaController taquillaController;
    private int cambio=0;
    private final VentaController ventaController=new VentaController();
    /**
     * Creates new form VentaBoletos
     * @param taquillaControler
     */
    public VentaBoletos(TaquillaController taquillaControler) {
        initComponents();
        this.taquillaController=taquillaControler;
        inicialidarbtg();
        btnEfectivo.setSelected(true);
        JTextArea textAreaDescripcion = new JTextArea(taquillaController.ventaActual());
        textAreaDescripcion.setBounds(300, 20, 400, 200);
        textAreaDescripcion.setBackground(Color.WHITE);
        textAreaDescripcion.setForeground(new Color(0, 102, 102)); // Establece el color del texto a blanco
        textAreaDescripcion.setEditable(false);

        // Asegúrate de que el panel tenga un layout nulo si usas setBounds
        pnlDescripcion.setLayout(null);

        pnlDescripcion.add(textAreaDescripcion);
        pnlDescripcion.revalidate(); // Revalida el panel
        pnlDescripcion.repaint(); // Redibuja el panel

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();
        pnlDescripcion = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnEfectivo = new javax.swing.JRadioButton();
        btnTarjeta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        btnProcesarVEnta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(0, 102, 102));
        pnlFondo.setForeground(new java.awt.Color(0, 102, 102));
        pnlFondo.setPreferredSize(new java.awt.Dimension(600, 400));

        pnlDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        pnlDescripcion.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout pnlDescripcionLayout = new javax.swing.GroupLayout(pnlDescripcion);
        pnlDescripcion.setLayout(pnlDescripcionLayout);
        pnlDescripcionLayout.setHorizontalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlDescripcionLayout.setVerticalGroup(
            pnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Procesar Venta Boletos");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total:");

        txtTotal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 102, 102));

        btnEfectivo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnEfectivo.setForeground(new java.awt.Color(0, 102, 102));
        btnEfectivo.setText("Efectivo");
        btnEfectivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnEfectivoStateChanged(evt);
            }
        });

        btnTarjeta.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnTarjeta.setForeground(new java.awt.Color(0, 102, 102));
        btnTarjeta.setText("Tarjeta");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elegir Formna de Pago");

        lblPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPago.setForeground(new java.awt.Color(255, 255, 255));
        lblPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPago.setText("Pago: ");

        txtPago.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPago.setForeground(new java.awt.Color(0, 102, 102));
        txtPago.setText("0");

        txtCambio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCambio.setForeground(new java.awt.Color(0, 102, 102));

        lblCambio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(255, 255, 255));
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambio.setText("Cambio:");

        btnProcesarVEnta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnProcesarVEnta.setForeground(new java.awt.Color(0, 102, 102));
        btnProcesarVEnta.setText("Procesar Venta");
        btnProcesarVEnta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarVEntaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPago))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCambio))
                            .addComponent(btnProcesarVEnta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEfectivo)
                            .addComponent(btnTarjeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnProcesarVEnta))
                    .addComponent(pnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarVEntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarVEntaActionPerformed
        // TODO add your handling code here:
        BoletoDAO bol=new BoletoDAO();
        if(regresarCambio()>=0 || modo.equalsIgnoreCase("credito")){
            int idVenta = ventaController.crearVenta(taquillaController.getEmpleado().getId(), -1, modo, "taquilla", taquillaController.getSubtotal());
            bol.agregarBoletos(ventaController.crearVentaBoletos(taquillaController, modo, "taquilla", taquillaController.getSubtotal()), idVenta);
            this.dispose();
            // Abrir el nuevo JFrame (Taquilla)
            Taquilla nuevaTaquilla = new Taquilla();
            nuevaTaquilla.setVisible(true);
        }
    }//GEN-LAST:event_btnProcesarVEntaActionPerformed

    private void btnEfectivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnEfectivoStateChanged
        // TODO add your handling code here:
        if (btnEfectivo.isSelected())
           mostrar();
        else
            ocultar();
    }//GEN-LAST:event_btnEfectivoStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Taquilla taquilla=new Taquilla();
        taquilla.setVisible(true);
        taquilla.setEmpleado(taquillaController.getEmpleado());
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JRadioButton btnEfectivo;
    private javax.swing.JButton btnProcesarVEnta;
    private javax.swing.JRadioButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void inicialidarbtg(){
        btgTipo.add(btnTarjeta);
        btgTipo.add(btnEfectivo);    
        txtCambio.setEditable(false);
        txtTotal.setEditable(false);
        txtTotal.setText(String.valueOf(taquillaController.getSubtotal()));
    }

    private void mostrar() {
        modo="efectivo";
        txtCambio.setVisible(true);
        txtPago.setVisible(true);
        lblCambio.setVisible(true);
        lblPago.setVisible(true);
    }

    private void ocultar() {
        modo="credito";
        txtCambio.setVisible(false);
        txtPago.setVisible(false);
        lblCambio.setVisible(false);
        lblPago.setVisible(false);
    }

    private double regresarCambio() {
        try {
            // Obtén el total como double en lugar de int
            double total = Double.parseDouble(txtTotal.getText()); 
            // Obtén el subtotal como double
            double subtotal = taquillaController.getSubtotal(); 
            // Calcula el cambio
            return total - subtotal; 
        } catch (NumberFormatException e) {
            System.err.println("Error al parsear el total: " + e.getMessage());
            return 0; // O manejar el error de otra manera
        }
    }

}
